const express = require('express')
const RestaurantController = require('../controller/RestaurantController')
const router = express.Router()
const multer = require("multer")
const upload = multer()


router.get('/one',upload.none(), RestaurantController.One )
router.get('/two',upload.none(), RestaurantController.Two)
router.get('/three',upload.none(), RestaurantController.Three)
router.get('/four',upload.none(), RestaurantController.Four)
router.get('/five',upload.none(), RestaurantController.Five)
router.get('/six',upload.none(), RestaurantController.Six)
router.get('/seven',upload.none(), RestaurantController.Seven)
router.get('/eight',upload.none(), RestaurantController.Eight)
router.get('/nine',upload.none(), RestaurantController.Nine)
router.get('/ten',upload.none(), RestaurantController.Ten)
router.get('/eleven',upload.none(), RestaurantController.Eleven)
router.get('/twelve',upload.none(), RestaurantController.Twelve)
router.get('/thirteen',upload.none(), RestaurantController.Thirteen)
router.get('/fourteen',upload.none(), RestaurantController.Fourteen)
router.get('/fifteen',upload.none(), RestaurantController.Fifteen)
router.get('/Sixteen',upload.none(), RestaurantController.Sixteen)
router.get('/seventeen',upload.none(), RestaurantController.Seventeen)
router.get('/eighteen',upload.none(), RestaurantController.Eighteen)
router.get('/nineteen',upload.none(), RestaurantController.Nineteen)
router.get('/twenty',upload.none(), RestaurantController.Twenty)
router.get('/twentyOne',upload.none(), RestaurantController.TwentyOne)
router.get('/twentyTwo',upload.none(), RestaurantController.TwentyTwo)
router.get('/twentyThree',upload.none(), RestaurantController.TwentyThree)
router.get('/twentyFour',upload.none(), RestaurantController.TwentyFour)
router.get('/twentyFive',upload.none(), RestaurantController.TwentyFive)
router.get('/twentySix',upload.none(), RestaurantController.TwentySix)
router.get('/twentySeven',upload.none(), RestaurantController.TwentySeven)
router.get('/twentyEight',upload.none(), RestaurantController.TwentyEight)
router.get('/twentyNine',upload.none(), RestaurantController.TwentyNine)
router.get('/thirty',upload.none(), RestaurantController.Thirty)
router.get('/thirtyOne',upload.none(), RestaurantController.ThirtyOne)
router.get('/thirtyTwo',upload.none(), RestaurantController.ThirtyTwo)
router.get('/thirtyThree',upload.none(), RestaurantController.ThirtyThree)
router.get('/thirtyFour',upload.none(), RestaurantController.ThirtyFour)
router.get('/thirtyFive',upload.none(), RestaurantController.ThirtyFive)
router.get('/thirtySix',upload.none(), RestaurantController.ThirtySix)
router.get('/thirtySeven',upload.none(), RestaurantController.ThirtySeven)
router.get('/thirtyEight',upload.none(), RestaurantController.ThirtyEight)
router.get('/thirtyNine',upload.none(), RestaurantController.ThirtyNine)
router.get('/forty',upload.none(), RestaurantController.Forty)
router.get('/fortyOne',upload.none(), RestaurantController.FortyOne)
router.get('/fortyTwo',upload.none(), RestaurantController.FortyTwo)
router.get('/fortyThree',upload.none(), RestaurantController.FortyThree)
router.get('/fortyFour',upload.none(), RestaurantController.FortyFour)
router.get('/fortyFive',upload.none(), RestaurantController.FortyFive)
router.get('/fortySix',upload.none(), RestaurantController.FortySix)
router.get('/fortySeven',upload.none(), RestaurantController.FortySeven)
router.get('/fortyEight',upload.none(), RestaurantController.FortyEight)
router.get('/fortyNine',upload.none(), RestaurantController.FortyNine)
router.get('/fifty',upload.none(), RestaurantController.Fifty)


module.exports = router